base_url = "https://dcariotti.me"
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
[paginator]
paginate_by = 3

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true

[extra]
name = "Santo Cariotti"
description = "Computer Programmer ðŸ§˜ from Italy"
avatar = "/avatar.jpg"
social_twitter = "dcariotti"
social_flickr = "dcariotti"
social_github = "dcariotti"
social_instagram = "arcticsanto"
social_linkedin = "santocariotti"
social_keybase = "dcariotti"
